# -----------------------------
# Database Configuration
# -----------------------------
database:
  catalog: "bytemaster"
  schema_name: "appdata"

# -----------------------------
# Dataset Configuration
# -----------------------------
datasets:
  AlternativeSourcing:
    table: "{catalog}.{schema_name}.AlternativeSourcing"
    join_keys: ["RunID", "ComponentId", "PlantId", "MaterialId"]
    update_columns: ["QtyAtRisk", "PotentialSaving", "ActualSaving", "Feedback", "CreatedTimestamp", "UserEmail"]
    filter_columns: ["RunID", "ComponentId", "PlantId", "MaterialId", "UserEmail", "Feedback"]

  BatchOptimization:
    table: "{catalog}.{schema_name}.BatchOptimization"
    join_keys: ["RunID", "ComponentId", "PlantId", "MaterialId"]
    update_columns: ["QtyAtRisk", "PotentialSaving", "ActualSaving", "Feedback", "CreatedTimestamp", "UserEmail"]
    filter_columns: ["RunID", "ComponentId", "PlantId", "MaterialId", "UserEmail", "Feedback"]

  ProductionScaling:
    table: "{catalog}.{schema_name}.ProductionScaling"
    join_keys: ["RunID", "ComponentId", "PlantId", "MaterialId"]
    update_columns: ["QtyAtRisk", "PotentialSaving", "ActualSaving", "Feedback", "CreatedTimestamp", "UserEmail"]
    filter_columns: ["RunID", "ComponentId", "PlantId", "MaterialId", "UserEmail", "Feedback"]

  ComponentExclusion:
    table: "{catalog}.{schema_name}.DimComponentExclusion"
    join_keys: ["ComponentId", "PlantId"]
    update_columns: ["ActiveFlag", "UpdatedTimestamp", "UserEmail"]
    filter_columns: ["ComponentId", "PlantId", "UserEmail"]

  DimSubstitution: 
    table: "{catalog}.{schema_name}.DimSubstitution"
    join_keys: ["ComponentId", "PlantId", "SubstituteOf"]
    update_columns: ["ActiveFlag", "UpdatedTimestamp", "UserEmail"]
    filter_columns: ["ComponentId", "PlantId", "UserEmail"]

  UserSettings:
    table: "{catalog}.{schema_name}.UserSettings"
    join_keys: ["PlantId"]
    update_columns: ["ApprovedMailID", "UserEmail", "UpdatedTimestamp"]
    filter_columns: ["PlantId", "ApprovedMailID"]