# -----------------------------
# Database Configuration
# -----------------------------
database:
  catalog: "bytemaster"
  schema_name: "appdata"

# -----------------------------
# Dataset Configuration
# -----------------------------
datasets:
  SourcingIntelligence:
    table: "{catalog}.{schema_name}.SourcingIntelligence"
    join_keys: ["RunID", "ComponentId", "PlantId", "MaterialId"]
    update_columns: ["QtyAtRisk", "PotentialSaving", "ActualSaving", "Feedback", "CreatedTimestamp", "UserEmail"]
    filter_columns: ["RunID", "ComponentId", "PlantId", "MaterialId", "UserEmail", "Feedback"]

  BatchConsolidation:
    table: "{catalog}.{schema_name}.BatchConsolidation"
    join_keys: ["RunID", "ComponentId", "PlantId", "MaterialId"]
    update_columns: ["QtyAtRisk", "PotentialSaving", "ActualSaving", "Feedback", "CreatedTimestamp", "UserEmail"]
    filter_columns: ["RunID", "ComponentId", "PlantId", "MaterialId", "UserEmail", "Feedback"]

  VolumeExpansion:
    table: "{catalog}.{schema_name}.VolumeExpansion"
    join_keys: ["RunID", "ComponentId", "PlantId", "MaterialId"]
    update_columns: ["QtyAtRisk", "PotentialSaving", "ActualSaving", "Feedback", "CreatedTimestamp", "UserEmail"]
    filter_columns: ["RunID", "ComponentId", "PlantId", "MaterialId", "UserEmail", "Feedback"]

  EligibilityBlacklist:
    table: "{catalog}.{schema_name}.EligibilityBlacklist"
    join_keys: ["ComponentId", "PlantId"]
    update_columns: ["ActiveFlag", "UpdatedTimestamp", "UserEmail"]
    filter_columns: ["ComponentId", "PlantId", "UserEmail"]

  AlternateMapping: 
    table: "{catalog}.{schema_name}.AlternateMapping"
    join_keys: ["ComponentId", "PlantId", "SubstituteOf"]
    update_columns: ["ActiveFlag", "UpdatedTimestamp", "UserEmail"]
    filter_columns: ["ComponentId", "PlantId", "UserEmail"]

  UserSettings:
    table: "{catalog}.{schema_name}.UserSettings"
    join_keys: ["PlantId"]
    update_columns: ["ApprovedMailID", "UserEmail", "UpdatedTimestamp"]
    filter_columns: ["PlantId", "ApprovedMailID"]